### PR TITLE
Pagination with first instead of last

### PR DESCRIPTION
**Pull request by Toosick**
With last you get some weird pagination. First seems more intuitive. Correct me if I'm wrong.

### CODE REVIEW

**Comment by djhi** [comment]
Thanks!

**Comment by mattfysh** [comment]
@Toosick @djhi is this fix going to be published to the npm registry? thanks!

**Comment by Toosick** [comment]
@mattfysh Definitely a question for @djhi . I don't have access.

**Comment by mattfysh** [comment]
Thanks @Toosick - after you merged this pull request, how did you pull the fix into your codebase?

**Comment by Toosick** [comment]
I have actually been running a fork of this repo and using that. It has some specific use cases to decrease browser requests but it should work regardless. https://github.com/iolap/aor-graphql

**Comment by mattfysh** [comment]
@djhi hate to pester, but can we get this fix pushed to npm? thanks!

**Comment by djhi** [comment]
Released as `v0.0.1` :)

**Pull request merged**
