### PR TITLE
[RFR] Schema reference

### PR DESCRIPTION
**Pull request by dervos**
See #20.

This is just a rough first pass at implementing it.

Improvements could be using a different format, [`.graphql`](https://www.graph.cool/docs/faq/graphql-sdl-schema-definition-language-kr84dktnp0/) instead of `.json`.

I am using it like this:
```jsx
import { __schema as schema } from './schema';
const introspectionOptions = {
  schema,
};
export default () =>
  buildApolloClient({
    client,
    introspection: introspectionOptions,
  });
```

The `./schema` file is a `schema.json` in `./scr` retrieved with [`get-graphql-schema --json <graphql_endpoint>`](https://github.com/graphcool/get-graphql-schema).

### CODE REVIEW

**Comment by djhi** [comment]
This is cool! Can you prefix your PR title with either `[WIP]` or `[RFR]` so that we know if you're still working on it or if it's Ready For Review? Thanks!

**Comment by dervos** [comment]
It's still a little too rough of an implementation to consider it [RFR]. The trade-offs between this solution and the introspection request would need to be documented.

I am also considering more flexible options, also keeping in mind the larger issue of introspection before the rendering of the `Admin` component. 

This solution lowers the initial rendering time at the cost of a significant increase of the bundle size because webpack will include the imported schema. Using this in combination with the [`create-react-app` webpack code-splitting feature](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#code-splitting) could decrease the main bundle size. The browser will then be able to cache the introspection chunk(which wouldn't change often). 

Do you have any comments?

**Comment by djhi** [comment]
> I am also considering more flexible options

Can you elaborate ?

I think it's great to have both options and we'll have to document the trade-offs for each. Also, an example app with the code splitting enabled would be really nice!

**Comment by dervos** [comment]
I think it's fine as is, after giving it some thought. I'll probably have more ideas when I use it for some time.

**Comment by djhi** [comment]
Ok! Can you document this new option ?

**Comment by dervos** [comment]
Would it be good to provide more information as to why you would possibly want to use the option?

**Comment by djhi** [comment]
Yes, that would be great too

**Comment by djhi** [comment]
Thanks!

**Pull request merged**
